In [38]:
"""
    Jupyter Notebook destinado para análise exploratória de acidentes e multas aplicadas em rodovias federais,
    durante o período de Carnaval, utilizando as bases públicas da Policia Rodoviária Federal (PRF) dos 
    últimos três anos (2023, 2024 e 2025).
"""
# Importações
import os
import sys
sys.path.append(os.path.abspath("../"))
from dotenv import load_dotenv
import pandas as pd
from databases.conector import GestaoBanco
from etl.pipeline_etl import PipelineETLAcidentes
load_dotenv()

True

In [39]:
'''
    Análise explotratória do DataFrame com dados brutos ainda sem limpeza.

'''

caminho_acidentes = os.getenv('CAMINHO_ACIDENTES_JP')
prf_db_url = os.getenv('DB_CONNECTION_STRING')

conexao = GestaoBanco(prf_db_url)
engine = conexao.conectar_banco()

pipeline = PipelineETLAcidentes(caminho_acidentes, engine)

pipeline.extrair_dados()
df_bruto = pipeline.acessar_df()
df_bruto.head()

Conexão com o MySQL testada e efetuada com sucesso!
Arquivos encontrados: 3
Extração concluida! O número total de registros é: 213418

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,classificacao_acidente,fase_dia,sentido_via,condicao_metereologica,tipo_pista,tracado_via,uso_solo,pessoas,mortos,feridos_leves,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop
0,496519.0,2023-01-01,domingo,02:00:00,ES,101,114,SOORETAMA,Ausência de reação do condutor,Saída de leito carroçável,Com Vítimas Feridas,Plena Noite,Crescente,Céu Claro,Simples,Reta,Não,1,0,1,0,0,0,1,1,"-19,09484877","-40,05095848",SPRF-ES,DEL04-ES,UOP01-DEL04-ES
1,496543.0,2023-01-01,domingo,03:40:00,SP,116,"113,1",TAUBATE,Entrada inopinada do pedestre,Atropelamento de Pedestre,Com Vítimas Fatais,Plena Noite,Decrescente,Céu Claro,Dupla,Reta,Sim,5,1,0,0,0,4,0,2,"-23,0445658","-45,58259814",SPRF-SP,DEL02-SP,UOP02-DEL02-SP
2,496590.0,2023-01-01,domingo,01:40:00,MT,163,1112,GUARANTA DO NORTE,Reação tardia ou ineficiente do condutor,Tombamento,NaN,Plena Noite,Crescente,Ignorado,Simples,Curva;Declive,Não,2,0,0,1,0,2,1,3,"-9,70020602","-54,87588757",SPRF-MT,DEL06-MT,UOP03-DEL06-MT
3,496610.0,2023-01-01,domingo,10:40:00,PR,376,"314,8",ORTIGUEIRA,Velocidade Incompatível,Tombamento,Sem Vítimas,Pleno dia,Crescente,Sol,Dupla,Curva,Não,2,0,0,0,1,2,0,3,"-23,985512","-51,083555",SPRF-PR,DEL07-PR,UOP02-DEL07-PR
4,496659.0,2023-01-01,domingo,14:55:00,MG,116,"569,4",MANHUACU,Acumulo de água sobre o pavimento,Colisão frontal,Com Vítimas Feridas,Pleno dia,Decrescente,Chuva,Simples,Declive;Curva,Não,4,0,0,2,1,1,2,3,"-20,10007457","-42,17884091",SPRF-MG,DEL06-MG,UOP03-DEL06-MG

In [40]:
'''
    Visualização detalhada da estrutura do DataFrame
'''
pd.set_option('display.max_columns', None)
df_bruto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 213418 entries, 0 to 213417
Data columns (total 30 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      213418 non-null  float64
 1   data_inversa            213418 non-null  object
 2   dia_semana              213418 non-null  object
 3   horario                 213418 non-null  object
 4   uf                      213418 non-null  object
 5   br                      213418 non-null  int64
 6   km                      213418 non-null  object
 7   municipio               213418 non-null  object
 8   causa_acidente          213418 non-null  object
 9   tipo_acidente           213418 non-null  object
 10  classificacao_acidente  213415 non-null  object
 11  fase_dia                213418 non-null  object
 12  sentido_via             213418 non-null  object
 13  condicao_metereologica  213418 non-null  object
 14  tipo_pista              213418 non-null  object
 15  tracado_via             213418 non-null  object
 16  uso_solo                213418 non-null  object
 17  pessoas                 213418 non-null  int64
 18  mortos                  213418 non-null  int64
 19  feridos_leves           213418 non-null  int64
 20  feridos_graves          213418 non-null  int64
 21  ilesos                  213418 non-null  int64
 22  ignorados               213418 non-null  int64
 23  feridos                 213418 non-null  int64
 24  veiculos                213418 non-null  int64
 25  latitude                213418 non-null  object
 26  longitude               213418 non-null  object
 27  regional                213396 non-null  object
 28  delegacia               213328 non-null  object
 29  uop                     213222 non-null  object
dtypes: float64(1), int64(9), object(20)
memory usage: 48.8+ MB

In [ ]:
'''
    Análise exploratória após tratamento do Data Frame.
'''
pipeline.transformar_dados()
pipeline.adicionar_colunas()


df_final = pipeline.acessar_df()
df_limpo.head()

Tratamento bem sucedido!
Adição de coluna bem sucedida!

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,classificacao_acidente,fase_dia,sentido_via,condicao_metereologica,tipo_pista,tracado_via,uso_solo,pessoas,mortos,feridos_leves,feridos_graves,ilesos,ignorados,feridos,veiculos,latitude,longitude,regional,delegacia,uop,carnaval
0,496519,2023-01-01,domingo,02:00:00,ES,101,114.0,SOORETAMA,Ausência de reação do condutor,Saída de leito carroçável,Com Vítimas Feridas,Plena Noite,Crescente,Céu Claro,Simples,Reta,Não,1,0,1,0,0,0,1,1,"-19,09484877","-40,05095848",SPRF-ES,DEL04-ES,UOP01-DEL04-ES,0
1,496543,2023-01-01,domingo,03:40:00,SP,116,113.1,TAUBATE,Entrada inopinada do pedestre,Atropelamento de Pedestre,Com Vítimas Fatais,Plena Noite,Decrescente,Céu Claro,Dupla,Reta,Sim,5,1,0,0,0,4,0,2,"-23,0445658","-45,58259814",SPRF-SP,DEL02-SP,UOP02-DEL02-SP,0
2,496590,2023-01-01,domingo,01:40:00,MT,163,1112.0,GUARANTA DO NORTE,Reação tardia ou ineficiente do condutor,Tombamento,NaN,Plena Noite,Crescente,Ignorado,Simples,Curva;Declive,Não,2,0,0,1,0,2,1,3,"-9,70020602","-54,87588757",SPRF-MT,DEL06-MT,UOP03-DEL06-MT,0
3,496610,2023-01-01,domingo,10:40:00,PR,376,314.8,ORTIGUEIRA,Velocidade Incompatível,Tombamento,Sem Vítimas,Pleno dia,Crescente,Sol,Dupla,Curva,Não,2,0,0,0,1,2,0,3,"-23,985512","-51,083555",SPRF-PR,DEL07-PR,UOP02-DEL07-PR,0
4,496659,2023-01-01,domingo,14:55:00,MG,116,569.4,MANHUACU,Acumulo de água sobre o pavimento,Colisão frontal,Com Vítimas Feridas,Pleno dia,Decrescente,Chuva,Simples,Declive;Curva,Não,4,0,0,2,1,1,2,3,"-20,10007457","-42,17884091",SPRF-MG,DEL06-MG,UOP03-DEL06-MG,0

In [42]:
print("------ VERIFICAÇÃO DO NÚMERO DE REGISTROS TOTAIS POR ANO ------")
print(f'O número total de registros brutos é: {len(df_bruto)}')
print(f'O número total de registro finais é: {len(df_final)}')
print('Acidentes Carnaval:', df_final['carnaval'].sum())
print("---------------------------------------------------------------")


print("------ VERIFICAÇÃO DO NÚMERO DE REGISTROS POR ANO ------")
print("\n Total Geral de Acidentes:")
print(df_final['data_inversa'].dt.year.value_counts().sort_index())

print("\n Só Acidentes no Período de Carnaval (Filtro Aplicado):")
print(df_final[df_final['carnaval'] == 1]['data_inversa'].dt.year.value_counts().sort_index())


print("------------------------------------------------")

------ VERIFICAÇÃO DO NÚMERO DE REGISTROS TOTAIS POR ANO ------
O número total de registros brutos é: 213418
O número total de registro finais é: 213418
Acidentes Carnaval: 3364
---------------------------------------------------------------
------ VERIFICAÇÃO DO NÚMERO DE REGISTROS POR ANO ------

 Total Geral de Acidentes:
data_inversa
2023    67766
2024    73156
2025    72496
Name: count, dtype: int64

 Só Acidentes no Período de Carnaval (Filtro Aplicado):
data_inversa
2023    1113
2024    1182
2025    1069
Name: count, dtype: int64
------------------------------------------------